# first Numpy Code
## For Exam 
- Python is Easy as Fuck

In [2]:
import numpy as np
import time

In [7]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# Numpy Arrays Vs Python List
- Numpy Arrays are faster (Optimized in C)
- Numpy Stores Data in Continous Memory Block
- Uses Less Memory (optimized Storage)
- Built-in Mathematical Operations
- Supports Direct Vectorized Operations 

In [10]:
print("At 1st going to do square of both python list and numpy array, and finding execution time for both")
size = 1_000_000
#python list
py_list = list(range(size))
start = time.time()
sq_list = [x ** 2 for x in py_list]
end = time.time()
print (f"Python List time= {end - start} seconds")

#numpy array
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"Numpy array time {end - start} seconds")

At 1st going to do square of both python list and numpy array, and finding execution time for both
Python List time= 1.07869291305542 seconds
Numpy array time 0.013143777847290039 seconds


In [12]:
#memory
import sys 
print(f"Python List size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy Array size =  {np_arr.nbytes} bytes")

Python List size = 8000056000000 bytes
Numpy Array size =  8000000 bytes


# 2D array in Numpy

In [19]:
arr2D = np.array([[1,2,3,], [4,5,6], [7,8,9,]])
print(arr2D)
print(arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [20]:
# Array with 0's
arr0 = np.zeros((2,3), dtype = "int64")
print(arr0, arr0.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [22]:
# Array with 1's
arr1 = np.ones((2,3), dtype = "int64")
print(arr1, arr1.shape)

[[1 1 1]
 [1 1 1]] (2, 3)


In [23]:
# Prefill Array with Some value Ex- 100
arr2 = np.full((3,4),100)
print(arr2)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [25]:
# identity Matrix , it is a square matrix
arr = np.eye(3)
print(arr, arr.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [27]:
# Range Function (Start, end , Step)

arr = np.arange(0,11,2)
print(arr, arr.shape)

[ 0  2  4  6  8 10] (6,)


In [28]:
# lin space- create evenly spaced arrays
arr = np.linspace(1,100,4)
print(arr)

[  1.  34.  67. 100.]


In [30]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)  
print(arr.size)  # total elements
print(arr.dtype)
print(arr.ndim) #2d or 3d

(3, 3)
9
int64
2


In [32]:
# Float Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


# Operations on Numpy Array

In [34]:
# Reshaping (2,3) -> (3,2)
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

# Flatterned
flat = arr.flatten()
print(flat, flat.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [36]:
# Indexing in 1D & 2D
# 1D
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[1])

1
2


In [37]:
# 2D
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][1])

2


In [3]:
# Fancy Indexing
arr = np.array([1,2,3,4,5,6])
idx = [0,1,3]
print(arr[idx])


[1 2 4]


In [5]:
# Boolean Indexing
arr = np.array([1,2,3,4,5,6])
print(arr[arr>2])
print(arr[arr%2 == 0])
print(arr[arr% 2!= 0 ])

[3 4 5 6]
[2 4 6]
[1 3 5]


In [6]:
# Slicing (start, end, step)
arr = np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


## Common Data Types
- Integers int32, int64
- floating points nums float32, float64
- Boolean bool
- complex nums complex64, complex128
- string s(byte-str) & u(unicode-str)
- objects : generic python objects-object