In [1]:
import numpy as np

## CREATING A 2D ARRAY USING np.array()

In [4]:
# Arithmetic Operations on 2D arrays
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Shape of a:", a.shape)
print("Number of rows:", a.shape[0])
print("Number of columns:", a.shape[1])

b = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(np.remainder(a, b))

Shape of a: (3, 3)
Number of rows: 3
Number of columns: 3
[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Array Indexing

In [13]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr[1,1])   # row = 1, col = 1 
print(arr[1:])
print(arr[0, :])
print(arr[1, :])

# cols
print(arr[:,0])
print(arr[:,1])

# SubSet of Arrays
# First 2 rows and first 2 columns
a_sub = arr[:2, :2]

print("Subset:")
print(a_sub)

5
[[4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[1 4 7]
[2 5 8]
Subset:
[[1 2]
 [4 5]]


### Modifying Subset

In [14]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

a_sub = arr[:2, :2]
a_sub[0, 0] = 12
print(a_sub)
print(arr)
# Notice:
# a[0,0] also changed from 1 to 12
# because a_sub is a view of a


[[12  2]
 [ 4  5]]
[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


### Transpose

In [15]:
arr = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(np.transpose(arr))
print(arr.T)

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


### Append Data

In [20]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Adding new row
new_row = np.array([[10, 11, 12]])

arr_with_row = np.append( arr, new_row, axis=0 )
arr_with_row2 = np.append( arr, [[1,2,3]], axis=0 )

print("\nAfter adding a row:")
print(arr_with_row)
print(arr_with_row2)


After adding a row:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [26]:
# Adding col
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Adding new col
new_col = np.array([10, 11, 12]).reshape(3,1)

arr_with_col = np.append( arr, new_col, axis=1 )
#arr_with_col2 = np.append( arr, [1,2,3], axis=1 )

print("\nAfter adding a col:")
print(arr_with_col)
#print(arr_with_col2)


After adding a col:
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


### Insert – Adding Data at a Specific Position

In [29]:
#Syntax
#np.insert(array, index, values, axis )
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

inserted = np.insert(arr, 1, [13, 15, 16], axis=0)
print(inserted)


[[ 1  2  3]
 [13 15 16]
 [ 4  5  6]
 [ 7  8  9]]


### Delete – Removing Data

In [30]:
#Syntax
#np.selete(array, index, axis)
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(np.delete(arr, 0, axis = 0))

[[4 5 6]
 [7 8 9]]


# Creating a Matrix

In [32]:
arr = np.matrix([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
 
#MATRIX PROPERTIES
 
print("\nShape of A:")
print(arr.shape)

print("\nNumber of rows:")
print(arr.shape[0])

print("\nNumber of columns:")
print(arr.shape[1])

print("\nTotal number of elements:")
print(arr.size)

# MODIFYING A MATRIX USING INDEXING
arr[0,0] = -7
print(arr)


Shape of A:
(3, 4)

Number of rows:
3

Number of columns:
4

Total number of elements:
12
[[-7  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
#ACCESSING MATRIX ELEMENTS
arr = np.matrix([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

print("\nSecond row:")
print(a[1, :])

print("\nThird column:")
print(a[:, 2])

print("\nElement at second row, third column:")
print(a[1, 2])


Second row:
[4 5 6]

Third column:
[3 6 9]

Element at second row, third column:
6


In [35]:
# Matrix Indexing
arr = np.matrix([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

print("First element:", arr[0, 0])
print("Second row, second column:", arr[1, 1])
print("Third row, fourth column:", arr[2, 3])

First element: 1
Second row, second column: 6
Third row, fourth column: 12


In [36]:
# Matrix Insertion
a_insert = np.matrix([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Syntax - np.insert(array, index, values, axis)

#  INSERT COLUMN  

column_new = np.matrix([
    [20],
    [30],
    [40]
])

a_column = np.insert( a_insert, 0, column_new, axis=1 )

print("\nAfter inserting column at index 0:")
print(a_column)


#   INSERT ROW  

row_new = np.matrix([
    [13, 14, 15, 16]
])

a_row = np.insert( a_insert, 0, row_new, axis=0 )

print("\nAfter inserting row at index 0:")
print(a_row)



After inserting column at index 0:
[[20 30 40  1  2  3  4]
 [20 30 40  5  6  7  8]
 [20 30 40  9 10 11 12]]

After inserting row at index 0:
[[13 14 15 16]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
# MATRIX ADDITION SUBSTRACTION MULTIPLICATION DIVISION

A = np.matrix([
    [0, 1, 2],
    [3, 4, 5]
])

B = np.matrix([
    [20, 21, 22],
    [23, 24, 25]
])

B_dot = np.matrix([
    [20, 21],
    [22, 23],
    [24, 25]
])

print(np.add(A, B))
print(np.subtract(A,B))
print(np.dot(A,B_dot))
print(np.matmul(A, B_dot))
print(A @ B_dot)
# A = 2 x 3
# B = 3 x 2
# Therefore:
# (2 x 3) x (3 x 2) = 2 x 2

[[20 22 24]
 [26 28 30]]
[[-20 -20 -20]
 [-20 -20 -20]]
[[ 70  73]
 [268 280]]
[[ 70  73]
 [268 280]]
[[ 70  73]
 [268 280]]


# DETERMINANT OF A MATRIX

In [42]:
A = np.array([
    [3, 1],
    [2, 4]
])

det_A = np.linalg.det(A)

print("\nDeterminant of A:")
print(det_A)

rank_A = np.linalg.matrix_rank(A)
print("\nRank of A:")
print(rank_A)


Determinant of A:
10.000000000000002

Rank of A:
2


In [43]:
# inverse of matrix
A = np.array([
    [3, 1],
    [2, 4]
])

A_inv = np.linalg.inv(A)
print("\nInverse of A:")
print(A_inv)


Inverse of A:
[[ 0.4 -0.1]
 [-0.2  0.3]]


In [46]:
#  SINGULAR MATRIX
B = np.array([
    [1, 2],
    [2, 4]
])

det_B = np.linalg.det(B)

print("\nDeterminant of B:")
print(det_B)

print("\nRank of B:")
print(np.linalg.matrix_rank(B))

if det_B == 0:
    print("\nB is a Singular Matrix.")
    print("Inverse of B does not exist.")
else:
    print("\nB is a Non-Singular Matrix.")
    print("Inverse exists.")


Determinant of B:
0.0

Rank of B:
1

B is a Singular Matrix.
Inverse of B does not exist.


In [50]:
#SYSTEM OF LINEAR EQUATIONS

# Equations:
# 3x + y + 2z = 2
# 3x + 2y + 5z = -1
# 6x + 7y + 8z = 3

# Coefficient Matrix A
A = np.array([
    [3, 1, 2],
    [3, 2, 5],
    [6, 7, 8]
])

# Constant Matrix B
B = np.array([
    2,
    -1,
    3
])

print("\nCoefficient Matrix A:")
print(A)

print("\nConstant Matrix B:")
print(B)

# SOLVING AX = B

solution = np.linalg.solve(A, B) # AX= B

print("\nSolution [x, y, z]:")
print(solution)

x = solution[0]
y = solution[1]
z = solution[2]

print("\nx =", x)
print("y =", y)
print("z =", z)


# DETERMINANT, RANK AND INVERSE OF COEFFICIENT MATRIX

print("\nDeterminant of coefficient matrix A:")
print(np.linalg.det(A))

print("\nRank of coefficient matrix A:")
print(np.linalg.matrix_rank(A))

print("\nInverse of coefficient matrix A:")
print(np.linalg.inv(A))


Coefficient Matrix A:
[[3 1 2]
 [3 2 5]
 [6 7 8]]

Constant Matrix B:
[ 2 -1  3]

Solution [x, y, z]:
[ 1.24242424  0.81818182 -1.27272727]

x = 1.2424242424242424
y = 0.818181818181818
z = -1.2727272727272725

Determinant of coefficient matrix A:
-33.0

Rank of coefficient matrix A:
3

Inverse of coefficient matrix A:
[[ 0.57575758 -0.18181818 -0.03030303]
 [-0.18181818 -0.36363636  0.27272727]
 [-0.27272727  0.45454545 -0.09090909]]
